org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.2

mod_version=1.1.0+26.2
maven_group=io.github.nineteenreincarnation
archives_base_name=wildwoven
mod_id=wildwoven
mod_name=Wildwoven
mod_license=MIT
mod_authors=Orrhisk
mod_description=A vanilla-oriented creature expansion focused on new mobs that naturally fit Minecraft.

loom_version=1.17.18
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.2

moddev_version=2.0.147
neo_version=26.2.0.87
loader_version_range=[4,)
minecraft_version_range=[26.2]
